<h1>Numpy</h1>
<h3>Notes on how control and use it</h3>

In [154]:
import numpy as np

DataTypes & Attributes

In [155]:
#Numpy's main datatypes is ndarray --> N dimensions array
array1 = np.array([1,2,3])
array1

array([1, 2, 3])

![<caption>](../pandas/recursos/anatomy_ndarray.png)   

Attributes

In [156]:
#See shape of ndarray as well as dimesions
array1.shape

(3,)

In [157]:
a2 = np.array([[1,2,3],
              [4,5,6]])
a2.shape

(2, 3)

In [158]:
#See number of dimensions...
a1 = array1
a1.ndim , a2.ndim

(1, 2)

In [159]:
#Check there data type
a1.dtype , a2.dtype

(dtype('int32'), dtype('int32'))

In [160]:
#See size
a1.size, a2.size

(3, 6)

In [161]:
#Even if their data type is int or float they are still ndarrays
type(a1)

numpy.ndarray

Create a DataF from NumPy array

In [162]:
import pandas as pd
df = pd.DataFrame(a2)

In [163]:
df

0  1  2
0  1  2  3
1  4  5  6

Create Arrays

In [164]:
#Basic method of creating an array
sample_arrray = np.array([1,2,3])
sample_arrray #Result of 1 dimensional NumPy Array

array([1, 2, 3])

In [165]:
#Ones() lets as specify dimensions and it will create an ndarray filled with ones
a4 = np.ones(5)
a4

array([1., 1., 1., 1., 1.])

In [166]:
a4.dtype

dtype('float64')

In [167]:
#To make it of ints you can specify dtype=
a4 = np.ones((2,3),dtype=int)
a4

array([[1, 1, 1],
       [1, 1, 1]])

In [168]:
#Arange function lets as create an arary using range params and start stop stepover
#a5 = np.arange(start,stop,stepover)
a5 = np.arange(0,10,2)
a5

array([0, 2, 4, 6, 8])

In [169]:
#Create Random Array
#random_array = np.random.randint(min_number,max_number,size=(dimensions))
random_array = np.random.randint(0,10,size=(3,5))
random_array

array([[8, 1, 4, 0, 3],
       [9, 2, 0, 4, 9],
       [2, 7, 7, 9, 8]])

In [170]:
#Most random way of doing it
random_array2 = np.random.random((2,2))
random_array2

array([[0.46923853, 0.09617226],
       [0.90337017, 0.11949047]])

In [171]:
#IMPORTANT CONCEPT PSEUDO RANDOM NUMBERS!!!!

#FOR THEM TO BE PSEUDO RANDOM... we actually want to do it random but save results for whenever someone
#Needs to see the notebook get same results

#np.random.seed(seed=x) --> Just generate before random numbers a seed
np.random.seed(seed=12)
random_array3 = np.random.random((2,2))
random_array3

array([[0.15416284, 0.7400497 ],
       [0.26331502, 0.53373939]])

VIEWING AND MANNIPULATING ARRAYS AND MATRIXES

In [172]:
#Get unique elements from an array
#It returns an array with only the unique cases
np.unique(random_array)

array([0, 1, 2, 3, 4, 7, 8, 9])

In [173]:
array_zero = np.zeros((3,3),dtype=int)
array_zero

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [174]:
np.unique(array_zero)

array([0])

In [175]:
#Bro the y are arrays check elements with FerroCarril and positions [0][5]
a2

array([[1, 2, 3],
       [4, 5, 6]])

In [176]:
a2[1][2]

6

In [177]:
a3 = np.random.randint(10, size=(2,3,3))
a3

array([[[0, 6, 1],
        [4, 5, 9],
        [2, 6, 0]],

       [[5, 8, 2],
        [9, 3, 4],
        [3, 1, 7]]])

In [178]:
#You can also string slice arrays
a3[:2, :2, :2]

array([[[0, 6],
        [4, 5]],

       [[5, 8],
        [9, 3]]])

MANIPULATION

 <h6>Arithmetic</h6>

In [179]:
a1

array([1, 2, 3])

In [180]:
a2 = np.ones(3)
a3 = a1 + a2
a3

array([2., 3., 4.])

In [181]:
#You can perform any basic arithmetic
a3 = a1 * a2
a3 = a3 - a1
a3

array([0., 0., 0.])

In [182]:
#note chekc on this later
#There is a thing called broadcast--> in wich a smaller array is broadcasted to a larger one in order to
#be able to do calculus on them

Aggregation

performing the same operation on a number of things...

In [183]:
#STANDARD DEVIATION
# A measure of how spread out a group of numbers is from the mean
#STD  = sqrt(variance)

np.std(a5)

2.8284271247461903

In [184]:
#Variance = measure of the average degree to wich each number is different from the mean
#Higher variance = wider range of numbers
#Lower variance = lower range of numbers

np.var(a5)

8.0

RESHAPING AND TRASPOSING

In [185]:
a2 = np.random.randint(1,10,size=(2,3))
a2

array([[1, 3, 7],
       [3, 1, 5]])

In [186]:
#RESHAPE
#returns an array containing same data but diff shape
#array.reshape(new_order_to_shape) --> this is done to fit and evade broadcasting problems

# Brodcasting: 2 dimensions are compatible when
#              1 ) they are equal
#              2 ) one of them is 1

a2.shape

(2, 3)

In [187]:
a2 =a2.reshape(2,3,1)
a2

array([[[1],
        [3],
        [7]],

       [[3],
        [1],
        [5]]])

In [188]:
a2.shape

(2, 3, 1)

Transpose

transpose switches axis in a matrix --> an 2,3 will become 3,2

In [189]:
a2.shape

(2, 3, 1)

In [190]:
a2.T.shape

(1, 3, 2)

Transpose is really usefull when it comes to Dot Products

In [191]:
np.random.seed(seed=1)

mat1 = np.random.randint(10,size=(5,3))
mat2 = np.random.randint(10,size=(5,3))

In [192]:
#Multiplying Matrixes normally would get the product-wise result a1 * a1
#If we want to multiply matrixes we need to do the dot product
np.dot(mat1, mat2.T)

array([[105, 116,  89, 180, 111],
       [ 10,  35,  35,  45,  30],
       [ 72,  76,  43, 114,  75],
       [ 54,  85,  87, 127,  76],
       [ 46,  57,  59,  91,  52]])

![<caption>](../pandas/recursos/dotwise.png) 

![<caption>](../pandas/recursos/dotwise2.png) 

COMPARISONS

In [193]:
#COMPARE MATRIXES
a1 > a2

array([[[False,  True,  True],
        [False, False, False],
        [False, False, False]],

       [[False, False, False],
        [False,  True,  True],
        [False, False, False]]])

SORTING ARRAYS

In [198]:
np.random.seed(seed=10)
random_array = np.random.randint(10, size=(3,5))
random_array

array([[9, 4, 0, 1, 9],
       [0, 1, 8, 9, 0],
       [8, 6, 4, 3, 0]])

In [195]:
#np.sort(ndarray) --> sorts per row
np.sort(random_array)

array([[0, 1, 4, 9, 9],
       [0, 0, 1, 8, 9],
       [0, 3, 4, 6, 8]])

In [196]:
#np.argsort(ndarray) --> sorts per index, tells us which index is coming first which second...
np.argsort(random_array)

array([[2, 3, 1, 0, 4],
       [0, 4, 1, 2, 3],
       [4, 3, 2, 1, 0]], dtype=int64)

In [200]:
#np.argsort(ndarray) --> tells us which index is the min value at... or argmax variant
np.argmin(random_array, axis=1) # if axis not specified it will give the first row only

array([2, 0, 4], dtype=int64)

TURN IMAGES INTO NUMBERS USING NUMPY

In [201]:
from matplotlib.image import imread

#imread(path to img)
panda = imread('./recursos/panda.png')

numpy.ndarray